1. [Toolbox Functionalities](#functionalities)
   * [Data Streams](#datastreams)
   * [Probabilistic Graphical Models](#pgms)
   * [Inference Engine](#inference)
   * [Learning Engine](#learning)
   * [Concept Drift](#conceptdrift)
   * [Links to MOA, Hugin and R](#librarylinks)

2. [Toolbox Architecture](#architecture)
   * [Description](#description)
   * [Java 8 Integration: Lambdas, streams, and functional-sytle programming](#java8)
   * [Installing AMIDST Toolbox](#installation)
       * [Installing MOALink](#installmoa)
       * [Installing HuginLink](#installhugin)
   * [Compiling & Running from the command line](#compilation)
3. [Contributing to AMIDST](#extension)
4. [Code Examples](#examples)
   * [Data Streams](#datastreamsexample)
   * [Random Variables](#variablesexample)
   * [Bayesian Networks](#bnexample)
       * [Creating Bayesian Networks](#bnnohiddenexample)
       * [Creating Bayesian Networks with latent variables](#bnhiddenexample)
       * [Modifying Bayesian Networks](#bnmodifyexample)
   * [I/O Functionality](#ioexample)
       * [I/O of Data Streams](#iodatastreamsexample)
       * [I/O of Bayesian Networks](#iobnsexample)
   * [Inference Algorithms](#inferenceexample)
       * [The Inference Engine](#inferenceengingeexample)
       * [Variational Message Passing](#vmpexample)
       * [Importance Sampling](#isexample)
   * [Learning Algorithms](#learningexample)
       * [Maximum Likelihood](#mlexample)
       * [Parallel Maximum Likelihood](#pmlexample)
       * [Streaming Variational Bayes](#svbexample)
       * [Parallel Streaming Variational Bayes](#psvbexample)
   * [Concept Drift Methods](#conceptdriftexample)
       * [Naive Bayes with Virtual Concept Drift Detection](#nbconceptdriftexample)
   * [HuginLink](#huginglinkexample)
       * [Models conversion between AMIDST and Hugin](#huginglinkconversionexample)
       * [I/O of Bayesian Networks with Hugin net format](#huginglinkioexample)
       * [Invoking Hugin's inference engine](#huginglinkinferenceexample)
       * [Invoking Hugin's Parallel TAN](#huginglinkTANexample)
   * [MoaLink](#moalinkexample)
       * [AMIDST Classifiers from MOA](#moalinkclassifiersexample)
       * [AMIDST Regression from MOA](#moalinkregressionsexample)
5. [API Java Doc](http://amidst.github.io/toolbox/javadoc/index.html)
6. [Citing AMIDST Toolbox](#cite)

<!--- [Maximum Likelihood with Fading](#mlfadingexample) [Streaming Variational Bayes with Fading](#svbfadingexample) -->
